env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - prettier
plugins:
  - react
  - react-hooks
rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/react-in-jsx-scope: off
  no-param-reassign: off
  no-unused-vars: warn
  # スプレッド構文のエラーを確認なしに変更
  "react/jsx-props-no-spreading": off
  # props をオプションで渡すことを許可
  "react/require-default-props": off
  semi:
    - error
    - never
  import/extensions:
    - error
    - js: never
      jsx: never
